FROM node:14.15.4-slim

USER node

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY --chown=node package*.json ./

RUN yarn

COPY --chown=node ./ .

RUN yarn build

EXPOSE 3000

CMD ["yarn", "run", "start:prod"]